start:
  latitude: 51.1234
  longitude: -150.679
  bearing: 150.0      # should correlate with 'build_bearing'
gameboard:
  height: 160
  width: 80
  build_bearing: ccw  # or 'cw'
  flag_offset: 20     # meters
