start:
  lat:  -35.122924  # decimal degrees
  long: 150.710536  # decimal degrees
  brg:  140.0       # should correlate with 'build_bearing'
gameboard:
  length:     160.0   # meters
  width:       80.0   # meters
  build_dir:    cw   # or 'cw'
  flag_offset: 20.0   # meters
